export const TOOL_ITEMS = {
  LINETOOL: "LINETOOL",
  RECTANGLETOOL: "RECTANGLETOOL",
  CIRCLETOOL: "CIRCLETOOL",
  PAINTBRUSHTOOL: "PAINTBRUSHTOOL",
  FONTTOOL: "FONTTOOL",
  ERASERTOOL: "ERASERTOOL",
  UNDOTOOL: "UNDOTOOL",
  REDOTOOL: "REDOTOOL",
  DOWNLOAD: "DOWNLOAD",
};

export const TOOL_ACTION_TYPES = {
  NONE: "NONE",
  DRAWING: "DRAWING",
};
export const BOARD_ACTIONS = {
  CHANGE_TOOL: "CHANGE_TOOL",
  DRAW_DOWN: "DRAW_DOWN",
  DRAW_UP: "DRAW_UP",
  DRAW_MOVE: "DRAW_MOVE",
};
