export const TOOL_ITEMS = {
  LINETOOL: "LINETOOL",
  RECTANGLETOOL: "RECTANGLETOOL",
  CIRCLETOOL: "CIRCLETOOL",
  BRUSHTOOL: "BRUSHTOOL",
  ARROWTOOL: "ARROWTOOL",
  FONTTOOL: "FONTTOOL",
  ERASER: "ERASER",
  UNDOTOOL: "UNDOTOOL",
  REDOTOOL: "REDOTOOL",
  DOWNLOAD: "DOWNLOAD",
};

export const TOOL_ACTION_TYPES = {
  NONE: "NONE",
  DRAWING: "DRAWING",
  ERASING: "ERASING",
};
export const BOARD_ACTIONS = {
  CHANGE_TOOL: "CHANGE_TOOL",
  DRAW_DOWN: "DRAW_DOWN",
  DRAW_UP: "DRAW_UP",
  DRAW_MOVE: "DRAW_MOVE",
  ERASE: "ERASE",
  CHANGE_ACTION_TYPE: "CHANGE_ACTION_TYPE",
};

export const COLORS = {
  BLACK: "#000000",
  RED: "#FF0000",
  GREEN: "#00FF00",
  BLUE: "#0000FF",
  YELLOW: "#FFFF00",
  CYAN: "#00FFFF",
  MAGENTA: "#FF00FF",
  SILVER: "#C0C0C0",
};
export const ARROW_LENGTH = 20;
export const ELEMENT_ERASE_THRESHOLD = 0.1;
export const TOOLBOX_ACTIONS = {
  CHANGE_STROKE: "CHAGE_STROKE",
  CHANGE_FILL: "CHANGE_FILL",
  CHANGE_SIZE: "CHANGE_SIZE",
};

export const FILL_TOOL_TYPES = [
  TOOL_ITEMS.RECTANGLETOOL,
  TOOL_ITEMS.CIRCLETOOL,
];
export const STROKE_TOOL_TYPES = [
  TOOL_ITEMS.BRUSHTOOL,
  TOOL_ITEMS.LINETOOL,
  TOOL_ITEMS.ARROWTOOL,
  TOOL_ITEMS.RECTANGLETOOL,
  TOOL_ITEMS.CIRCLETOOL,
];

export const SIZE_TOOL_TYPES = [
  TOOL_ITEMS.LINETOOL,
  TOOL_ITEMS.ARROWTOOL,
  TOOL_ITEMS.RECTANGLETOOL,
  TOOL_ITEMS.CIRCLETOOL,
];
